### ISSUE TITLE
one docker file

### ISSUE THREAD

**Issue by lvthillo** [thanhson1085/angular-admin-seed#19]
Is it a good idea to have only one dockerfile?
Isn't it an improvement to have a dockerfile for the app (which will start from a nginx image). And a second dockerfile in server (which will start from a nodejs image). So you will have 2 containers and you can let them work together.

Because docker is telling us: one process for each container. (okay it's working when you're doing it all together but it's against the 'rules'

**Comment by thanhson1085** [comment]
Yep, I know. I just make it simply for the development. We should remove Nginx and Redis from dockerfile, and make a orchestration with docker compose

**Comment by lvthillo** [comment]
Thanks, when I don't want to use docker compose. Is it enough to --link those 2 containers with the command? (I will have 1 container with nginx (and the /dist folder hosted) and one container with node.js

**Comment by thanhson1085** [comment]
yes, you can use `--link` in that case.
